import subprocess
import filecmp
import sys
import os
import glob

def find_latest_output(prefix="API_Transformed_"):
    """Find the most recent output file generated by the script."""
    files = glob.glob(f"{prefix}*.json")
    if not files:
        return None
    return max(files, key=os.path.getmtime)

def run_test():
    input_file = "sample_input.txt"
    config_file = "config/default_config.json"
    expected_output = "expected_output.txt"
    script = "legacy_to_api_demo.py"

    # Clean up any previous outputs that match the pattern
    for f in glob.glob("API_Transformed_*.json"):
        os.remove(f)

    print(f"Running demo script with input: {input_file} and config: {config_file}")
    result = subprocess.run(
        [sys.executable, script, input_file, config_file],
        capture_output=True,
        text=True
    )

    print(result.stdout)
    if result.returncode != 0:
        print(f"❌ Script failed with error:\n{result.stderr}")
        return

    output_file = find_latest_output()
    if not output_file:
        print("❌ No output file found after running the script.")
        return

    print(f"Comparing output file '{output_file}' with expected output '{expected_output}'...")
    # Compare files ignoring whitespace differences in the last line newline
    files_match = filecmp.cmp(output_file, expected_output, shallow=False)

    if files_match:
        print("✅ Test Passed: Output matches expected output.")
    else:
        print("❌ Test Failed: Output differs from expected.")
        print("You can use diff to inspect differences.")

if __name__ == "__main__":
    run_test()
